import React from 'react'

export const About = () => {
  return (
    <div>
This is about component
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, nesciunt voluptatum! Corrupti quibusdam dignissimos enim suscipit doloremque quia, voluptas, vel fugiat est veritatis sapiente reiciendis. Eaque perspiciatis nihil recusandae. Quas, dolore vel. At itaque officiis nesciunt, explicabo soluta, rem ab ea ut velit, quaerat error sint. Quaerat fugit saepe, amet fuga a doloremque, fugiat modi ut animi dolorem, deleniti sequi libero numquam! Eos maxime tempore corrupti reiciendis at nisi facilis, magni mollitia facere officia quod reprehenderit incidunt, neque iste voluptate dolores officiis. Maxime, nulla aliquam. Eaque ex doloremque velit explicabo quod, quas unde natus maxime vel amet at enim odio minus nostrum neque perspiciatis est nisi corrupti ducimus reiciendis nam adipisci eligendi voluptas. Quia earum aliquid quam qui eligendi iste tempora nam asperiores reprehenderit. Quibusdam consequatur, praesentium modi qui ratione perspiciatis pariatur nobis maxime sed tenetur repellat fuga, perferendis maiores numquam aspernatur officia porro atque, laboriosam corrupti consequuntur doloribus eum eaque. Laborum eligendi esse ad magni ullam debitis? Voluptates inventore optio architecto cumque illum officiis nemo recusandae omnis rem! Eos, sunt assumenda esse sit veritatis ratione reiciendis enim aperiam libero explicabo maxime illum fugit, in quaerat, quos tempore necessitatibus veniam culpa nisi nemo a repellat. Modi quod ipsam quas ullam eum aperiam, eveniet vel dolores cumque quidem, est commodi ipsa optio? Accusamus rerum explicabo, neque commodi itaque tempora architecto optio ab sapiente expedita, hic dolorem fugiat. Minus voluptatum consectetur doloremque consequatur, beatae praesentium eveniet inventore, velit eaque quaerat sint ducimus nam dolore temporibus voluptatibus ad consequuntur expedita sit similique ab reprehenderit. Est, asperiores eaque praesentium tenetur consectetur quas itaque vitae. Earum, sapiente ipsa pariatur eaque inventore quaerat, quo quos ratione, recusandae culpa nobis non tempora obcaecati quidem error quasi nam voluptates dolores harum. Tempora quia voluptate reiciendis eveniet pariatur natus minus sequi molestias delectus odit, eius quam, maiores saepe quae voluptatem, rem quos doloribus. Illo veritatis dolorum porro id ex voluptatem ipsam sapiente, voluptatum sint explicabo laboriosam quod sequi libero tempore odio eligendi delectus dolorem aliquid veniam maxime?</p>

    </div>
  )
}
